pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=nryanov-auto
    actions:
      label:
        add: [dependency-update]
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=nryanov-auto
      - "status-success=scalafmt (adopt@1.11, 2.13.6)"
      - "status-success=Scala 2.12.15, Java adopt@1.8"
      - "status-success=Scala 2.13.6, Java adopt@1.8"
      - "status-success=Scala 2.12.15, Java adopt@1.11 "
      - "status-success=Scala 2.13.6, Java adopt@1.11"
    actions:
      merge:
        method: merge
